name: CS

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkcs:
    name: 'Basic CS and QA checks ${{ matrix.php }} ${{ matrix.dependencies }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - "lowest"
          - "highest"
        include:
          - php-version: "8.2"
            composer-options: "--ignore-platform-reqs"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
          tools: composer, cs2pr
      - uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ matrix.composer-options }}"

      - name: Get Composer home directory
        id: composer-home
        run: |
          echo "::set-output name=dir::$(composer config home)"

      - name: Install PHP dependencies
        uses: ramsey/composer-install@v2

      - name: Install composer-normalize
        run: composer global require ergebnis/composer-normalize

      - name: Make Composer packages available globally
        run: |
          echo "${PWD}/vendor/bin" >> $GITHUB_PATH
          echo "${{ steps.composer-home.outputs.dir }}/vendor/bin" >> $GITHUB_PATH

      - name: Lint PHP files
        run: phpcs -q --report=checkstyle | cs2pr

      - name: Analyze PHP files
        run: composer run-script analyze

      - name: Lint composer.json
        run: composer normalize --dry-run
